# Generated by Django 4.2.11 on 2024-03-21 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('idProfession', models.AutoField(primary_key=True, serialize=False)),
                ('lib', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('idSpecialite', models.AutoField(primary_key=True, serialize=False)),
                ('lib', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionnelDeSante',
            fields=[
                ('idProfessionnelDeSante', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=60)),
                ('prenom', models.CharField(max_length=60)),
                ('dateNaiss', models.DateField()),
                ('dateMaj', models.DateField()),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carte.profession')),
                ('specialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carte.specialite')),
            ],
        ),
    ]
