# Generated by Django 4.2.11 on 2024-03-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionneldesante',
            name='identifiantPP',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
