# Generated by Django 4.2.11 on 2024-06-10 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0002_professionneldesante_identifiantpp'),
    ]

    operations = [
        migrations.AddField(
            model_name='acte',
            name='professionnel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='carte.professionneldesante'),
        ),
        migrations.AddField(
            model_name='commune',
            name='demandeSoin',
            field=models.CharField(default='50', max_length=120),
        ),
        migrations.AddField(
            model_name='commune',
            name='populatio2535',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='commune',
            name='population3545',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='commune',
            name='population4555',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='commune',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='carte.commune'),
        ),
        migrations.AddField(
            model_name='profession',
            name='codeProfession',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='professionneldesante',
            name='commune',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='carte.commune'),
        ),
        migrations.AddField(
            model_name='professionneldesante',
            name='infrastructure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='carte.infrastructure'),
        ),
        migrations.AddField(
            model_name='specialite',
            name='codeSpecialite',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='professionneldesante',
            name='specialite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carte.specialite'),
        ),
        migrations.CreateModel(
            name='PonDist',
            fields=[
                ('idPonDist', models.AutoField(primary_key=True, serialize=False)),
                ('temps', models.CharField(max_length=120)),
                ('communeC', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commune1', to='carte.commune')),
                ('communeV', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commune2', to='carte.commune')),
            ],
        ),
    ]
