# Generated by Django 4.2.11 on 2024-06-11 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0003_acte_professionnel_commune_demandesoin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commune',
            old_name='populatio2535',
            new_name='population2535',
        ),
    ]
