# Generated by Django 4.2.11 on 2024-06-12 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0004_rename_populatio2535_commune_population2535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionneldesante',
            name='identifiantPP',
        ),
    ]
