# Generated by Django 4.2.11 on 2024-06-12 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0005_remove_professionneldesante_identifiantpp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infrastructure',
            old_name='codeCatIn',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='professionneldesante',
            old_name='dateNaiss',
            new_name='age',
        ),
        migrations.RemoveField(
            model_name='infrastructure',
            name='FINESSJ',
        ),
        migrations.RemoveField(
            model_name='infrastructure',
            name='equipement',
        ),
        migrations.RemoveField(
            model_name='infrastructure',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='infrastructure',
            name='libCatIn',
        ),
        migrations.RemoveField(
            model_name='infrastructure',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='infrastructure',
            name='telephone',
        ),
        migrations.AddField(
            model_name='equipement',
            name='infrastructure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carte.infrastructure'),
        ),
    ]
