# Generated by Django 4.2.11 on 2024-06-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0006_rename_codecatin_infrastructure_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructure',
            name='type',
            field=models.CharField(max_length=120),
        ),
    ]
