# Generated by Django 4.2.11 on 2024-06-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0007_alter_infrastructure_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionneldesante',
            name='charge',
            field=models.IntegerField(null=True),
        ),
    ]
