# Generated by Django 4.2.11 on 2024-06-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carte', '0008_professionneldesante_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionneldesante',
            name='age',
        ),
        migrations.AddField(
            model_name='professionneldesante',
            name='agePS',
            field=models.IntegerField(null=True),
        ),
    ]
